# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.13.0-bullseye

# Install python and pip
RUN apt-get update 
RUN apt-get install -y cmake   
RUN apt-get install -y libaio1 wget unzip iputils-ping openssh-server curl nano alien git 
RUN git config --global user.name "nguyen bao"
RUN git config --global user.email "ng.tanquocbao@gmail.com"
RUN mkdir /var/run/sshd


#install java
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean;
# install .net
RUN wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y apt-transport-https
RUN apt-get update
RUN apt-get install -y dotnet-sdk-6.0

# Setup SSH server
RUN echo 'root:00dantruong' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile


# talib:

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    && wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
    && tar -xzf ta-lib-0.4.0-src.tar.gz \
    && cd ta-lib/ \
    && ./configure --prefix=/usr \
    && make \
    && make install \
    && rm -rf ta-lib-0.4.0-src.tar.gz ta-lib/

RUN pip install ta-lib


EXPOSE 2344

# start ssh service: service ssh start

